## 작업형1

### 문제1
1. 대륙('continent')별 맥주 소비량(‘beer_servings’)의 평균을 계산하고, 평균이 가장
 큰 대륙을 찾으시오.
2. 1번에서 찾은 대륙에서 맥주 소비량이 5번째로 많은 국가(‘country’)의 맥주 소비량을 구하시오.

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/8_1/drinks.csv")

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa

In [ ]:
#1번풀이 대륙으로 묶은 다음에 소비량 평균, 평균이 가장 큰 대륙을 찾으시오.
#groupby는 함수여서 안에 continent는 소괄호, beer_servings는 그 칼럼선택
cond = df.groupby('continent')['beer_servings'].mean()
top_cond = cond.idxmax()

In [ ]:
# 2. 1번에서 찾은 대륙에서 맥주 소비량이 5번째로 많은 국가(‘country’)의 맥주 소비량을 구하시오.d

df1 = df['continent'] == top_cond

df = df[df1]
df = df.sort_values('beer_servings', ascending=False)
df.iloc[4,1]
# df.iloc[4]['beer_servings']

313

### 문제2
1. ‘관광객비율’이 두 번째로 높은 국가의 ‘사업’ 방문객 수를 a라고 정의하시오.
2. ‘관광’이 두 번째로 높은 국가의 ‘공무’ 방문객 수를 b라고 정의하시오.
3. a와 b의 합을 구하시오.
- 방문객 합계 = 관광 + 공무 + 사업 + 기타
- 관광객 비율 = 관광 / 방문객 합계

In [ ]:
# 방법1
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/8_1/tourist.csv")


#1)방문객 합계 및 관광객 비율 계산
df['방문객합계'] = df['관광'] + df['공무'] + df['사업'] + df['기타']
df['관광객비율'] = df['관광'] / df['방문객합계']
# 관광객비율 = df['관광'] / 방문객합계
df.head()


#2) 조건에 맞는 값 찾기
a = df.sort_values('관광객비율',ascending=False).iloc[1,3] #203


b = df.sort_values('관광', ascending= False).iloc[1, 2] #238


print(a+b)

441

In [ ]:
# 방법2
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/8_1/tourist.csv")

#1)방문객 합계 및 관광객 비율 계산
df['방문객합계'] = df['관광'] + df['공무'] + df['사업'] + df['기타']
df['관광객비율'] = df['관광'] / df['방문객합계']
# 관광객비율 = df['관광'] / 방문객합계
df.head()


#2) 조건에 맞는 값 찾기
#nlargest하면 n번쨰로 가장 큰거 찾는 함수!(자동 내림차순되어서 보여지기때문에 순서대로 나올 수 밖에없음)
df.nlargest(2, '관광객비율').iloc[1, 3]

203

### 문제3
1. 주어진 데이터에서 ‘co’와 ‘nmhc’ 컬럼을 각각 Min-Max 스케일링하시오.
2. 스케일링된 ‘co’, ‘nmhc’ 컬럼의 표준편차를 각각 구하시오.
3. ‘co’ 컬럼의 표준편차에서 ‘nmhc’ 컬럼의 표준편차를 뺀 값을 소수점 3자리로 반올림하여 구하시오.
- Min-Max 스케일링 = (X - min_X) / (max_X - min_X)
- X 변수의 최솟값: min_X
- X 변수의 최댓값: max_X

In [ ]:
# 방법1
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/8_1/chem.csv")
from sklearn.preprocessing import MinMaxScaler
df.head()

#1) Min_max 스케일링 (데이터프레임으로 만들기)
#df['co']에서는 그 두개로 나눠서 해야함
scaler = MinMaxScaler()
df['co_scaled'] = scaler.fit_transform(df[['co']])
df['nmhc_scaled'] = scaler.fit_transform(df[['nmhc']])


#2) 표준편차 계산(판다스 표준편차)
co_std = df['co_scaled'].std()   #0.2856516497116944
nmhc_std = df['nmhc_scaled'].std()  #0.3030617020578397


#3) 표준편차 차이 계산 및 반올림
#round 할때 안에다가 , 찍고해야함 괄호 안에 하면 다른 값이나옴

print(round(co_std - nmhc_std,3))

-0.017

In [ ]:
# 표준편차가 pandas 표준편차가 있고,  numpy 표준편차가 있음, 여기 시험에서는 pandas 표준편차만 알아도 충분함.
# numpy방법으로 되는게 위에서는 스케일링할때 df하고[]괄호 쳤는데, 넘파이에서는 df[]없이 하는 경우를 말함
# df['co_scaled'] = scaler.fit_transform(df[['co']])
# df['nmhc_scaled'] = scaler.fit_transform(df[['nmhc']])

#넘파이경우
# co_scaled = scaler.fit_transform(df[['co']])
# nmhc_scaled = scaler.fit_transform(df[['nmhc']])

In [ ]:
# 방법2
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/8_1/chem.csv")

from sklearn.preprocessing import MinMaxScaler
df.head()

#1) Min_max 스케일링 (데이터프레임으로 만들기)
#df['co']에서는 그 두개로 나눠서 해야함
scaler = MinMaxScaler()
co_scaled = scaler.fit_transform(df[['co']])
nmhc_scaled = scaler.fit_transform(df[['nmhc']])
type(co_scaled)


#2) 표준편차 계산(판다스 표준편차)
co_std = co_scaled.std()   #0.2856516497116944
nmhc_std = nmhc_scaled.std()  #0.3030617020578397

#3) 표준편차 차이 계산 및 반올림
#round 할때 안에다가 , 찍고해야함 괄호 안에 하면 다른 값이나옴

print(round(co_std - nmhc_std,3))

#★지금 반올림하고, 뺴기만 해서 값이 같은거지, 만약에 반올림이 달랐거나, 다른 수식이 있거나, 다른걸 물고서 계산하거나 했으면 값이 완전히 달랐을 수 도 있음
#그래서 이 방법2는 사용하지 않고 방법 1 pandas 방식으로 만 하기! 즉df[].std식으로 df으로

-0.017

1.print(round(co_std - nmhc_std, 3))
이 코드는 co_std - nmhc_std의 값을 먼저 계산하고, 그 결과를 소수점 셋째 자리까지 반올림합니다. 반올림된 결과를 출력합니다.

예:
만약 co_std - nmhc_std = 1.234567이라면, round(1.234567, 3)의 결과는 1.235가 됩니다.

2. print(round(co_std - nmhc_std), 3)
이 코드는 co_std - nmhc_std의 값을 먼저 계산하고, 그 결과를 정수로 반올림합니다.
즉, 소수점을 고려하지 않고 정수로 만든 값을 출력합니다.
3이라는 추가적인 값은 출력 형식에서 무시되기 때문에 효과가 없습니다.

예:
만약 co_std - nmhc_std = 1.234567이라면, round(1.234567)의 결과는 1이 됩니다.